"""Synthetic, deterministic fixtures. Outputs are not from any AI provider."""

from typing import Any

from src.domain.research import ExperimentDefinition


def replay(
    definition: ExperimentDefinition,
    model: str,
    prompt_index: int,
    repeat: int,
    simulate_failure: bool = False,
) -> dict[str, Any]:
    if simulate_failure and model == "fixture-b" and prompt_index == 0 and repeat == 0:
        return {
            "status": "failed",
            "raw_text": "",
            "error": "simulated_provider_timeout",
            "exclusion_reason": "Synthetic failure example; excluded from eligible denominator",
        }
    thresholds = [9, 7, 6, 4] if model == "fixture-a" else [7, 8, 5, 6]
    selected = [
        b
        for i, b in enumerate(definition.brands)
        if (repeat * 3 + prompt_index + i * 2) % 10 < thresholds[i % 4]
    ]
    descriptions = {
        "Notion": "combines documentation with flexible project views.",
        "Asana": "offers structured task ownership and team planning.",
        "Linear": "focuses on issue tracking and software delivery.",
        "Monday": "offers configurable workflows and visual planning.",
    }
    lines = [
        "SYNTHETIC FIXTURE. This response is authored for interface testing, "
        "not generated by a model.",
        "",
        "For this illustrative scenario, consider:",
    ]
    lines += [
        f"{i + 1}. {brand} {descriptions.get(brand, 'is included in this test scenario.')}"
        for i, brand in enumerate(selected)
    ]
    lines += ["", "Evaluate the workflow with your team before choosing."]
    if (prompt_index + repeat) % 3 != 0 and selected:
        lines += [
            "Illustrative source URL (not retrieved):",
            "https://example.com/research/project-tools",
        ]
    return {
        "status": "succeeded",
        "raw_text": "\n".join(lines),
        "error": None,
        "exclusion_reason": None,
    }
